Algoritmo COMPAÑIA
	ESCRIBIR" CUANTOS VENDEDORES SON "
	LEER V
	N<-1
	ESCRIBIR" SUELDO BASE "
	LEER S
	Mientras N<=V Hacer
		ESCRIBIR " COSTO DE VENTA "
		LEER V1
		LEER V2
		LEER V3
		C<-(V1+V2+V3)*0.15
		S<-S+C
		M<-N+1
		ESCRIBIR " LAS COMISIONES TOTALES ",C
		ESCRIBIR " SUELDO ",S
	Fin Mientras
FinAlgoritmo
