Algoritmo CAJERO
	Escribir "CUANTOS CLIENTES SON "
	LEER CL
	Mientras T<=CL Hacer
		ESCRIBIR "INGRESA EL NUMERO DE ARTICULO "
		LEER NA
		ESCRIBIR "INGRESA EL PRECIO "
		LEER PA
		D<-NA*PA
		T<-T+1
		ESCRIBIR "EL TOTAL DE LA COMPRA ",D
		S<-S+D
	 Fin Mientras
	ESCRIBIR "LA TIENDA GANO ",S
FinAlgoritmo
